### ISSUE TITLE
Workspace did not detect in tooling

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/distribution#14]
**Description:**
When starting the siddhi tooling, the message popped out as "Unable to read sample file" as below.
<img width="1792" alt="unable-to-read-sample" src="https://user-images.githubusercontent.com/18663444/54413135-c9179b00-471a-11e9-8a80-cea0da9d5324.png">

When trying to access the workspace, the workspace did not detected by the tool.
<img width="1792" alt="workspace-not-detected" src="https://user-images.githubusercontent.com/18663444/54413227-f2d0c200-471a-11e9-8123-93b5462cdbfb.png">

However, I can open files in the workspace using `File->Open file`.

**Comment by pcnfernando** [comment]
Fixed with #69
