### ISSUE TITLE
How to run it with eclipse?

### ISSUE THREAD

**Issue by runc** [siddhi-io/distribution#168]
Because it uses osgi, but I am not familiar with how to build a development environment

**Comment by pcnfernando** [comment]
Can you elaborate more on your use-case? Do you want to build the distributions manually?
[siddhi-io/distribution](https://github.com/siddhi-io/distribution) repository maintains the source code of the siddhi-runner and siddhi-tooling runtimes.

Please refer to the official documentation [here](https://siddhi-io.github.io/siddhi/documentation/siddhi-5.x/siddhi-as-a-local-microservice-5.x/).

**Comment by runc** [comment]
thanks，I want to build a local development environment of distribution , but no documentation。

**Comment by pcnfernando** [comment]
You need to first clone the repo from Github. Let the directory be <USER_HOME>/distribution
`git clone https://github.com/siddhi-io/distribution.git`

Install maven plug-ins in your eclipse
From Eclipse, 
`Import project > Existing Maven Projects > Open <USER_HOME>/distribution/pom.xml`

The build steps are available [here](https://github.com/siddhi-io/distribution/blob/master/README.md).

**Comment by mohanvive** [comment]
Resolving the issue since query has been answered. Please reopen if you need further assistance on this.
