### ISSUE TITLE
Siddhi Cloud Native CI/CD Process Implementation

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/distribution#170]
**Description:**
We have two runtimes as Siddhi Runner and Siddhi Tooling. We need to improve how these runtimes play alongside the CI/CD process.

This also includes integration with Jenkins, Dockerhub & Kubernetes.

**Comment by mohanvive** [comment]
Moved from https://github.com/siddhi-io/siddhi/issues/1326 ...

**Comment by pcnfernando** [comment]
To complete CI/CD story need to resolve #171 #247

**Comment by mohanvive** [comment]
Closing the issue since sub tasks are completed..
