### ISSUE TITLE
Editor Improvements related to CI/CD Story

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/distribution#171]
**Description:**
Due to the improvements related to CI/CD of Siddhi, there are some improvements/changes required in the Siddhi editor. Hence, this issue is created to track that.

**Comment by pcnfernando** [comment]
Downloading docker and K8 artifacts handled on #247

**Comment by mohanvive** [comment]
Handled through https://github.com/siddhi-io/distribution/issues/247
