### ISSUE TITLE
Documentation on CI/CD Story of Siddhi

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/distribution#172]
**Description:**
Need a proper documentation/article which explains the end to end CI/CD story of Siddhi. This document will be the guide for external users to achieve the complete CI/CD cycle with Siddhi.

**Comment by mohanvive** [comment]
Created by @pcnfernando in https://medium.com/@pcnfernando/c33150721b5d ...

**Comment by pcnfernando** [comment]
Published in [Siddhi Tech Blog](https://medium.com/siddhi-io/building-an-efficient-ci-cd-pipeline-for-siddhi-c33150721b5d)
