### ISSUE TITLE
Distribution build artifacts are not shown for jenkins build

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/distribution#222]
**Description:**
There are two build artifacts in "distribution" repo of Siddhi. They are siddhi-runner-x.x.x.zip and siddhi-tooling-x.x.x.zip. 

But once Jenkins release job is completed, we cannot find the above build artifacts in the Jenkins web UI. We ended up getting that from nexus repo.

We need to add below file paths to list down above files as build artifacts.

```
distribution/runner/target/siddhi-runner-x.x.x.zip
distribution/tooling/target/siddhi-tooling-x.x.x.zip
```

**Comment by maheshika** [comment]
Added the paths to Jenkins.
