### ISSUE TITLE
[Documentation] Document the default configurations used in distributions

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#245]
**Description:**
As part of cleaning the configurations to make it simple, the default configurations will be removed from the deployment.yml. Hence, we need to document the default configurations being used during runtime for the user's reference.
It also would provide a reference to the configuration schemas for different components in a single place.

**Affected Product Version:**
5.1.0-m1

**Comment by niveathika** [comment]
Fixed with https://github.com/siddhi-io/www/pull/32
