### ISSUE TITLE
Support downloading docker & K8 artifacts from editor

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#247]
**Description:**
At the moment, we use the Siddhi Tooling editor to develop Siddhi applications. Once we create a functional Siddhi application, we need to create a [Siddhi Custom Resource](https://github.com/siddhi-io/siddhi-operator/releases) object with the created Siddhi application to deploy it in a kubernetes environment. We need to provide support to create this Siddhi Custom Resouce object from the tooling editor itself to minimize this gap between development and deployment.

Furthermore, we need to support the user to create a docker image bundling the needed extensions and third-party dependencies from the developing environment (Siddhi Tooling editor).

My suggestion would be to the below tools in the editor.
- Download Siddhi Kubernetes artifacts.
- Download Docker image.

Download Siddhi Kubernetes artifacts would download a zip containing the Siddhi custom resource object and the needed pre-requisites.
Download Docker image would create a zip with the corresponding version of the runner docker build file with the needed dependencies.

**Affected Product Version:**
5.1.0-m1

**Comment by niveathika** [comment]
Dev discussion started in https://groups.google.com/forum/?hl=en#!topic/siddhi-dev/KUa3Zns6VBY

**Comment by niveathika** [comment]
UI feature implementation is ongoing in branch https://github.com/siddhi-io/distribution/tree/export-feature
