### ISSUE TITLE
Moving extension samples to tooling distribution

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#299]
**Description:**
With Siddhi Tooling distribution v5.1.0-m2, we are only bundling 9 mandatory samples. It would be easier for the user, if we move the samples specific to extensions from [samples/artifacts](https://github.com/wso2/product-sp/tree/master/modules/samples/artifacts).
Before moving them, we would have to clean the descriptions.

**Affected Product Version:**
v5.1.0-m2

**Comment by mohanvive** [comment]
Completed by @dasuni-30 @Malintha1996 @PrabodDunuwila @sahandilshan @SinthujanSintha ...
