### ISSUE TITLE
Osgi test failure in Appveyor build

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#336]
**Description:**
SiddhiStoreAPITestcase.testSelectAllWithSuccessResponse() test fails intermittently since the test Siddhi app fails to deploy with No extension exist for source:tcp exception.
 
**Affected Product Version:**
master branch

**OS, DB, other environment details and versions:**    
Appveyor  

**Steps to reproduce:**
When Appveyor runs build for a PR

**Comment by mohanvive** [comment]
This is fixed with https://github.com/siddhi-io/siddhi/pull/1507 ...
