### ISSUE TITLE
No results found error for distributionStrategy operator

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#364]
**Description:**
_No results found error for **distributionStrategy**_ under Operators in Siddhi Editor.
If no content for the said operator, we should not show it under the Operators.

**Comment by niveathika** [comment]
Along with incrementalaggregator:count(), this is an internal siddhi extension, we use to denote count() aggregations inside NamedAggregations, should not be shown here, or copied as incrementalaggregator:count()
