### ISSUE TITLE
[Exporting to Docker/K8] Zip file with same name

### ISSUE THREAD

**Issue by CharukaK** [siddhi-io/distribution#365]
**Description:**
Zip file created from the K8 export feature has the same name as the file exported through Docker export feature

**Affected Product Version:**
siddhi-tooling-5.1.0-alpha

**Steps to reproduce:**
1) Create a siddhi app and use the K8 export and Docker export feature
2) Follow through the steps and export the file

**Assignees**
@BuddhiWathsala

**Comment by BuddhiWathsala** [comment]
Fixed in here https://github.com/siddhi-io/distribution/pull/383
