### ISSUE TITLE
[Exporting to Docker/K8] No proper error handling if the export fails

### ISSUE THREAD

**Issue by niveathika** [siddhi-io/distribution#377]
**Description:**
$subject, if the export microservice call fails, the user is not notified and only console log is available

**Affected Product Version:**
5.1.0-alpha

**Steps to reproduce:**
1. Export K8 artifact
2. For kubernetes config, give a string
3. Try to export

**Comment by pcnfernando** [comment]
Fixed with https://github.com/siddhi-io/distribution/pull/507
