### ISSUE TITLE
Parser does not provide service configurations for TCP sources

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/distribution#388]
**Description:**
When we deploy Siddhi apps with NATS source using Siddhi operator the service creation does not happen. The reason was parser did not return configurations for the service creation when we have TCP sources. For users, we are recommending to disable ingress creation for TCP sources and create ingress manually. Since this service configuration does not return by the parser lead the user to not only create ingress but also to create K8s service by themselves. Therefore it is better to return TCP ports from the parser.

**Suggested Labels:**
Feature improvement

**Affected Product Version:**
5.1.0-alpha

**OS, DB, other environment details and versions:** 
siddhi-operator:0.2.0-alpha   

**Steps to reproduce:**
Deploy Siddhi app like below using Siddhi operator.
```sql
@App:name("PowerConsumptionSurgeDetection")
@App:description("App consumes events from HTTP as a JSON message of { 'deviceType': 'dryer', 'power': 6000 } format and inserts the events into DevicePowerStream, and alerts the user if the power consumption in 1 minute is greater than or equal to 10000W by printing a message in the log for every 30 seconds.")

/*
    Input: deviceType string and powerConsuption int(Joules)
    Output: Alert user from printing a log, if there is a power surge in the dryer within 1 minute period. 
            Notify the user in every 30 seconds when total power consumption is greater than or equal to 10000W in 1 minute time period.
*/

@source(
    type='nats',
    cluster.id='siddhi-stan',
    destination = 'PowerStream', 
    bootstrap.servers='nats://siddhi-nats:4222',
    @map(type='text')
)
define stream DevicePowerStream(deviceType string, power int);

@sink(type='log', prefix='LOGGER')
define stream PowerSurgeAlertStream(deviceType string, powerConsumed long);

@info(name='surge-detector')
from DevicePowerStream#window.time(1 min)
select deviceType, sum(power) as powerConsumed
group by deviceType
having powerConsumed > 10000
output every 30 sec
insert into PowerSurgeAlertStream;
```

**Comment by pcnfernando** [comment]
Seems siddhi-io-nats source returns null which would have been the reason for the empty deployment info.
Refer https://github.com/siddhi-io/siddhi-io-nats/blob/master/component/src/main/java/io/siddhi/extension/io/nats/source/NATSSource.java#L165

Also, we might have to revisit all the sources which are being bundled in the Siddhi Runner distribution.

**Comment by BuddhiWathsala** [comment]
As I tested we can access the internal NATS source even without a Kubernetes service. Therefore up to now we do not need that service creation for TCP sources. You can find out more details about external TCP access to the Siddhi sources using [Siddhi documentation](https://siddhi.io/en/v5.1/docs/siddhi-as-a-kubernetes-microservice/).

**Comment by pcnfernando** [comment]
@BuddhiWathsala for port-forwarding, we either need to know about the pod name or the service name. Also, in a production environment, we cannot configure port-forwarding for the external connections. Accessing port-forwarding is only possible for admin privileged.
Hence, let's keep the issue open till we fix sources to expose the deployment configurations.

Let's document handling tcp connections where we request user to avoid auto ingress creation and create ingress or other means to expose the tcp connections. If user decides to use auto ingress creation, steps to configure the nginx to allow tcps.

Does that make sense?
