### ISSUE TITLE
[Editor] When app becomes faulty the simulator controls are not reverted back

### ISSUE THREAD

**Issue by suhothayan** [siddhi-io/distribution#461]
**Description:**
When a Faulty App is saved the simulator control looks like bellow: 
<img width="311" alt="Screen Shot 2019-09-28 at 1 52 50 AM" src="https://user-images.githubusercontent.com/3785208/65799935-e67df500-e192-11e9-8a80-cc837be4f08a.png">

When "start and send" is clicked, the app becomes faulty, and the faulty log gets printed. 
But the simulator control still in "send" as bellow and not reverted back to "start and send": 
<img width="304" alt="Screen Shot 2019-09-28 at 1 52 29 AM" src="https://user-images.githubusercontent.com/3785208/65800069-2f35ae00-e193-11e9-8c1c-20a074ba6e05.png">

**Comment by mohanvive** [comment]
@suhothayan can u please share the faulty Siddhi app?

**Comment by suhothayan** [comment]
Steps to reproduce

Deploy any valid app 
E.g : 
```
@app:name('Alert-Processor') 

define stream TemperatureStream(roomNo string, temp double);

@sink(type='log') 
define stream AlertStream(roomNo string, avgTemp double);

@info(name='AlertQuery') 
from TemperatureStream#window.time(5 min)
select roomNo, avg(temp) as avgTemp
group by roomNo
insert into AlertStream;
```

Go to simulator "Start and Send" a couple of events. 
Now edit the app to have an error (e.g change `avgTemp` in select to `avTemp`) and save. 
You will be able to see that the simulator will be still in `Send` so you can send events. 
(here I did not see the faulty error)

But when you edit the app and before I get 
"Siddhi App Alert-Processor successfully deployed." if I send events then I'm getting the faulty error.

I think this can be fixed, by reverting the simulator buttons, when the app start and stop buttons are reverted (like when we start editing the app).

**Comment by niveathika** [comment]
Fixed with https://github.com/siddhi-io/distribution/pull/556
