### ISSUE TITLE
[Tooling] Issues in Samples

### ISSUE THREAD

**Issue by niveathika** [siddhi-io/distribution#470]
**Description:**
$subject

**Comment by niveathika** [comment]
@Malintha1996 No need to make jars OSGi explicitly, we can just drop to jars folder, https://github.com/siddhi-io/distribution/blob/master/samples/artifacts/EventCollection/RecieveKafkaInAvroFormat.siddhi#L12

**Comment by niveathika** [comment]
@PrabodDunuwila Make the stream name as OutputStream, there is no filter do, it cannot be LowProductionStream,

https://github.com/siddhi-io/distribution/blob/master/samples/artifacts/EventCollection/ReceiveTCPinBinaryFormat.siddhi#L51

**Comment by niveathika** [comment]
@dasuni-30 

1. Review the stream name, same as @PrabodDunuwila issue  1.Also, there is wso2SP in the comments.

**Comment by niveathika** [comment]
@SinthujanSintha ,

1. PublishNatsinTextFormat -> Sample would not work without a NATS server running already, Testing the Sample, step 3 as prerequiste

**Comment by niveathika** [comment]
@sahandilshan

**Comment by niveathika** [comment]
@dasuni-30 , @SinthujanSintha , @sahandilshan , @PrabodDunuwila , @Malintha1996 Spell check!

**Comment by SinthujanSintha** [comment]
> @SinthujanSintha ,
> 
> 1. PublishNatsinTextFormat -> Sample would not work without a NATS server running already, Testing the Sample, step 3 Move it to Step 1. Review the stream names



> @SinthujanSintha ,
> 
> 1. PublishNatsinTextFormat -> Sample would not work without a NATS server running already, Testing the Sample, step 3 Move it to Step 1. Review the stream names

db32f82ccca5922cbc4fd90316d06a215bd4bf43 This commit fixed the above correction
