### ISSUE TITLE
Document REST APIs for Siddhi Tooling Runtime

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/distribution#498]
**Description:**
Add documentation for below APIs.
Tooling: Editor and Simulator

**Comment by suhothayan** [comment]
Improve the On-Demand Query API guide

**Comment by mohanvive** [comment]
> Improve the On-Demand Query API guide

Added in https://github.com/siddhi-io/www/pull/79

**Comment by mohanvive** [comment]
We have decided not to add REST APIS of editor for external users.
