### ISSUE TITLE
[Static rule processing guide] Connection Error when send the curl request to Siddhi docker run time artifact

### ISSUE THREAD

**Issue by SinthujanSintha** [siddhi-io/distribution#549]
**Description:**
I got a connection error when I try to send the curl request to the Siddhi docker run time artifact .
The error like in below image.
![Screenshot from 2019-10-03 21-40-21](https://user-images.githubusercontent.com/40277159/66144450-781fb380-e626-11e9-94cd-a097d1dd7c0a.png)

I have created  Siddhi docker run time artifact based on Siddhi use case guide in the Siddi site (https://siddhi.io/en/v5.1/docs/guides/database-static-rule-processing/guide/#siddhi-docker-configurations).

**Affected Product Version:**
siddhi-tooling-5.1.1
**OS, DB, other environment details and versions:**    
OS :- siddhi-tooling-5.1.1
DB :-mysql 5.7.27

**Comment by pcnfernando** [comment]
@BuddhiWathsala

**Comment by pcnfernando** [comment]
Fixed with https://github.com/siddhi-io/www/pull/108

**Comment by mohanvive** [comment]
Guide is working fine as expected but observed that some guidelines are missing. That might be a reason for above issue. @BuddhiWathsala has fixed those doc gaps in https://github.com/siddhi-io/www/pull/108 ...
