### ISSUE TITLE
Debugger gets stuck when an event is sent

### ISSUE THREAD

**Issue by CharukaK** [siddhi-io/distribution#555]
**Description:**
Event simulation form gets stuck when an event is sent while in the debugging mode of the siddhi editor as shown below
![Screen Shot 2019-10-04 at 5 21 20 PM](https://user-images.githubusercontent.com/18122888/66205607-6fcd8400-e6cb-11e9-9a9e-4e9810c38b67.png)

The thread hangs [waitForSystemStabilization() method of io.siddhi.core.util.snapshot.SnapshotService](https://github.com/siddhi-io/siddhi/blob/c57264bb1f2051ef845c0f49ec3f3a03dd1bd2a8/modules/siddhi-core/src/main/java/io/siddhi/core/util/snapshot/SnapshotService.java#L754)  class.

**Suggested Assignees:**
@suhothayan 

**Steps to reproduce:**
1. Start the Siddhi app in debugging mode of the editor
2. Navigate to the Single Event Simulation form of the editor and select the app which is in debugging mode select a stream and sent an event with the appropriate values

**Comment by niveathika** [comment]
@CharukaK, We have decided to depreciate debugger support on the editor. It has been removed from SiddhiTooling 5.1.0
