### ISSUE TITLE
[Editor] Debug in Simulator is still visible 

### ISSUE THREAD

**Issue by suhothayan** [siddhi-io/distribution#577]
**Description:**
currently it shows 
![image](https://user-images.githubusercontent.com/3785208/66251286-431d7900-e76c-11e9-801c-e17e89a8e0df.png)

this section need to be hidden/removed 
![image](https://user-images.githubusercontent.com/3785208/66251334-adceb480-e76c-11e9-9029-34f8fa9aadb3.png)

**Comment by pcnfernando** [comment]
This has been fixed. Did you try with the latest fixes
https://github.com/siddhi-io/distribution/pull/574.

Are you not saving the faulty Siddhi app?
@niveathika Can you please try this
