### ISSUE TITLE
[Editor] When docker push fails for authentication reason, cannot re push 

### ISSUE THREAD

**Issue by suhothayan** [siddhi-io/distribution#580]
**Description:**
2nd docker export with push is causing a broken pipe exception. 

Also, validate the credentials before allows the user to clink export or next.

**Comment by pcnfernando** [comment]
Tried pushing with wrong credentials and thereafter retrying with correct credentials; worked as expected. Did the test multiple times in different browsers as well.

**Comment by pcnfernando** [comment]
Cannot reproduce in 5.1.0 GA release.
