### ISSUE TITLE
[Doc] Look into using swagger files to generate Rest API guide

### ISSUE THREAD

**Issue by niveathika** [siddhi-io/distribution#631]
**Description:**
$subject as it will be easy to maintain. 

Swagger files also should be maintained for each API. As of now only 1/2 of APIs have updated swagger files

**Comment by mohanvive** [comment]
Isn't above a duplicate of https://github.com/siddhi-io/distribution/issues/644  ?

**Comment by niveathika** [comment]
Yes it is. hence closing
