### ISSUE TITLE
[Tooling] Change K8s export process to use predefined Docker image

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/distribution#636]
**Description:**
Currently, the K8s export process of Siddhi tooling does not have a mechanism to set a predefined Docker image. Hence, we need to support that predefined image input in the export process. 

Also, this can be added as an initial step which would select either of the following:
1. Build and push a Docker image using the Siddhi tooling or 
1. Select an existing image and export the artifacts

**Suggested Labels:**
Feature improvement

**Affected Product Version:**
5.1.0

**Steps to reproduce:**
Export K8s artifacts using Siddhi tooling. Try to use an existing Docker image.

**Comment by niveathika** [comment]
Reopening as the PR was reverted, by https://github.com/siddhi-io/distribution/pull/679
