### ISSUE TITLE
[Tooling] Syntax error shown while templating variables

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#719]
**Description:**
When we try to template some specific operators, tooling shows an syntax error even when a value is set for the templated variables.
My guess is this because of the frontend syntax validations we run within the ACE editor.

**Steps to reproduce:**
Template the length size of a length batch window.
Populate the set variable.

![image](https://user-images.githubusercontent.com/15815199/69332547-ebd05b00-0c7c-11ea-84b1-55c83f56c615.png)

When this Siddhi application is deployed in runner with the environment variables set correctly, it runs as expected.

**Comment by suhothayan** [comment]
Fixed in Siddhi 5.1.2 release
