### ISSUE TITLE
[Tooling][Design View] Configuring app annotations fails 

### ISSUE THREAD

**Issue by pcnfernando** [siddhi-io/distribution#770]
**Description:**
When I try to configure app annotations from the design view, it returns me empty fields even-though App name and descriptions are available. 

I observed the below exception in the web browser console at the time.
```
Uncaught TypeError: self.formUtils.changeHeightOfPerfectScroller is not a function
    at AppAnnotationForm.generatePropertiesForm (app-annotation-form.js:46)
    at FormBuilder.DefineFormForAppAnnotations (form-builder.js:120)
    at HTMLDivElement.<anonymous> (design-grid.js:127)
```
**Affected Product Version:**
v5.1.2 RC1

**Comment by suhothayan** [comment]
Fixed in https://github.com/siddhi-io/distribution/pull/778
